apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-devops
  labels:
    app: final-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-devops
  template:
    metadata:
      labels:
        app: final-devops
    spec:
      containers:
        - name: final-devops-container
          image: harikrishnan330/final-devops:latest
          ports:
            - containerPort: 3000
